# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/jupyter_core-4.6.3-python_3.7-on-linux_canary, last modified Tue Mar 31 08:55:26 2020
# ------------------------------------------------

package:
    name: jupyter_core
    version: 4.6.3
source:
    sha256: 394fd5dd787e7c8861741880bdf8a00ce39f95de5d18e579c74b882522219e7e
    url: https://pypi.io/packages/source/j/jupyter_core/jupyter_core-4.6.3.tar.gz
build:
    entry_points:
        - jupyter = jupyter_core.command:main
        - jupyter-migrate = jupyter_core.migrate:main
        - jupyter-troubleshoot = jupyter_core.troubleshoot:main
    number: '0'
    script: /tmp/build/80754af9/jupyter_core_1585645177526/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps -vv
    string: py37_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.1.1 0
        - certifi 2019.11.28 py37_1
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_0
        - openssl 1.1.1e h7b6447c_0
        - pip 20.0.2 py37_1
        - python 3.7.7 hcf32534_0_cpython
        - readline 8.0 h7b6447c_0
        - setuptools 46.1.3 py37_0
        - setuptools_scm 3.4.3 py_0
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.7,<3.8.0a0
        - traitlets
test:
    commands:
        - jupyter -h
        - jupyter-migrate -h
        - jupyter-troubleshoot --help
        - pip check
    imports:
        - jupyter_core
    requires:
        - nose
        - pip
        - pytest
about:
    dev_url: https://github.com/jupyter/jupyter_core
    doc_source_url: https://github.com/jupyter/jupyter_core/tree/master/docs
    doc_url: https://jupyter-core.readthedocs.io
    home: https://jupyter.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: Core common functionality of Jupyter projects.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - bollwyvl
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
