# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/krb5-1.17.1-on-linux_64, last modified Mon Dec 16 23:01:26 2019
# ------------------------------------------------

package:
    name: krb5
    version: 1.17.1
source:
    sha256: 8bdedbfb0bbb245217e23290437916d70b315514e6f7cc088b6e82d1310afe0b
    url: https://github.com/krb5/krb5/archive/krb5-1.17.1-final.tar.gz
build:
    number: '0'
    run_exports:
        - krb5 >=1.17.1,<1.18.0a0
    string: h173b8e3_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526hebd4dad_5
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - bison 3.4 he6710b0_1
        - ca-certificates 2019.11.27 0
        - flex 2.6.4 ha10e3a4_1
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - perl 5.26.2 h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.7.5 h0371630_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.27 0
        - libedit 3.1.20181209 hc058e9b_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - tk 8.6.8 hbc83047_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libedit >=3.1.20181209,<3.2.0a0
        - libedit >=3.1.20181209,<4.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - openssl >=1.1.1d,<1.1.2a
        - tk >=8.6.8,<8.7.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX krb5
    requires:
        - python 3.7.*
about:
    home: http://web.mit.edu/kerberos/
    license: MIT
    license_file: doc/notice.rst
    summary: A network authentication protocol.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mariusvniekerk
        - mingwandroid
        - ocefpaf
        - pelson
